# url which leads to changelog page
ASSETS_CHANGELOG_URL = ''  # TODO: set it, when it's formed
DEFAULT_DEPRECATION_RATE = 25

ASSETS_REPORTS = {
    'ENABLE': False,
    'INVOICE_REPORT': {'SLUG': 'invoice-report'},
    'RELEASE-ASSET': {'SLUG': 'release-asset'},
    'LOAN-ASSET': {'SLUG': 'loan-asset'},
    'RETURN-ASSET': {'SLUG': 'return-asset'},
    'TEMP_STORAGE_PATH': '/tmp/',
}

ASSETS_TRANSITIONS = {
    'ENABLE': False,
    'SLUGS': {
        'RELEASE-ASSET': 'release-asset',
        'LOAN-ASSET': 'loan-asset',
        'RETURN-ASSET': 'return-asset',
        'CHANGE-HOSTNAME': 'change-hostname',
    }
}

ASSET_HIDE_ACTION_SEARCH = False

# force locale during pdf raport genration
GENERATED_DOCS_LOCALE = None

ASSET_HOSTNAME_TEMPLATE = {
    'prefix': '{{ country_code|upper }}{{ code|upper }}',
    'postfix': '',
    'counter_length': 5,
}

# automatically assign domain hostname to asset in edit and bulk forms
ASSETS_AUTO_ASSIGN_HOSTNAME = False
if locals().get('ASSETS_AUTO_ASSIGN_HOSTNAME'):
    # this text will be displayed as a help tip next to the hostname form field
    HOSTNAME_FIELD_HELP_TIP = 'Autogenerated if owner & model are set.'
